EmployeeCrud/Controllers/EmployeeController.cs
using EmployeeCrud.Data;
using EmployeeCrud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.IdentityModel.Protocols;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeCrud.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationContext context;


        public EmployeeController(ApplicationContext context)
        {
            this.context = context;
        }


        public IActionResult Index()
        {
            var result = context.Employees.ToList();

            var joinTable = (from r in context.Employees
                             join mng in context.Managers on r.ManagerId equals mng.Id 
                             select new EmployeeData()
                             {Id=r.Id,
                               Name=r.Name,
                               Salary=r.Salary,
                               City=r.City,
                               State=r.State,
                               ManagaerId=mng.Id,
                               ManagerName=mng.Name
                             }
                             ).ToList();


            ViewBag.data = joinTable;


            return View(result);
            }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.manager = context.Managers.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Create(string Name, string State, string City, decimal Salary, string mng)

        {

            var emp = new Employee()
            {
                Name = Name,
                State=State,
                City=City,
                Salary=Salary,
               ManagerId=Convert.ToInt32(mng)


            };
            context.Employees.Add(emp);
            context.SaveChanges();
            TempData["Create"] = "Employee Created!!";
            return RedirectToAction("Index");


            /* if (ModelState.IsValid)
             {

                 var emp = new Employee()
                 {
                     Name = model.Name,
                     State = model.State,
                     City = model.City,
                     Salary = model.Salary,
                     ManagerId = model.ManagerId

                 };
                 context.Employees.Add(emp);
                 context.SaveChanges();
                 TempData["Create"] = "Employee Created!!";
                 return RedirectToAction("Index");
             }
             else
             {
                 TempData["C_error"] = "Empty field can't Submit!!";
                 return View();
             }
 */

        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var emp = context.Employees.SingleOrDefault(e => e.Id == Id);

            /*  var emp =  from e in context.Employees
                                 where e.Id == id 
                                 select new Employee() ;

              Employee data = emp.FirstOrDefault();*/
            ViewBag.manager = context.Managers.ToList();
            var result = new Employee()
            {
                Name = emp.Name,
                State = emp.State,
                City = emp.City,
                Salary = emp.Salary,
                ManagerId=emp.ManagerId
            };

            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(int Id,string Name, string State, string City, decimal Salary, string mng)
        {
            var emp = new Employee()
            {
                Id = Id,
                Name =Name,
                State =State,
                City =City,
                Salary =Salary,
                ManagerId = Convert.ToInt32(mng)
            };
            context.Employees.Update(emp);
            context.SaveChanges();
            TempData["Edit"] = "Employee Updated!!";
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int Id)
        {
            var emp = context.Employees.SingleOrDefault(e => e.Id == Id);
            context.Employees.Remove(emp);
            context.SaveChanges();
            TempData["Delete"] = "Employee Deleted!!";
            return RedirectToAction("Index");
        }
    }
}
public class EmployeeData
{

    public int Id { get; set; }
    
    public string Name { get; set; }
   
    public string State { get; set; }
   
    public string City { get; set; }

    public decimal Salary { get; set; }
    public int ManagaerId { get; set; }
    public string ManagerName { get; set; }
}

EmployeeCrud/Controllers/ManagerController.cs
using EmployeeCrud.Data;
using EmployeeCrud.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeCrud.Controllers
{
    public class ManagerController : Controller
    {
        private readonly ApplicationContext context;
        public ManagerController(ApplicationContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            ViewBag.manager = context.Managers.ToList();
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Manager model)
        {
            if (ModelState.IsValid)
            {
                var mng = new Manager()
                {
                    Name = model.Name,
                    State = model.State,
                    City = model.City,
                    Salary = model.Salary
                };
                context.Managers.Add(mng);
                context.SaveChanges();
                TempData["Create"] = "Manager Created!!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["C_error"] = "Empty field can't Submit!!";
                return View(model);
            }

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var emp = context.Managers.SingleOrDefault(e => e.Id == id);

            /*  var emp =  from e in context.Employees
                                 where e.Id == id 
                                 select new Employee() ;

              Employee data = emp.FirstOrDefault();*/

            var result = new Manager()
            {
                Name = emp.Name,
                State = emp.State,
                City = emp.City,
                Salary = emp.Salary
            };

            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(Manager model)
        {
            var emp = new Manager()
            {
                Id = model.Id,
                Name = model.Name,
                State = model.State,
                City = model.City,
                Salary = model.Salary
            };
            context.Managers.Update(emp);
            context.SaveChanges();
            TempData["Edit"] = "Manager Updated!!";
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var emp = context.Managers.SingleOrDefault(e => e.Id == id);
            context.Managers.Remove(emp);
            context.SaveChanges();
            TempData["Delete"] = "Manager Deleted!!";
            return RedirectToAction("Index");
        }
    }
}

EmployeeCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeCrud</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Manager" asp-action="Index">Manager</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmployeeCrud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>